"""
state.py
--------
Defines the shared state object that flows between every node in the graph.

In LangGraph, "state" is just a dictionary-like object that each node reads
from and writes back to. Think of it as a shared clipboard that gets passed
around the graph, with each node adding or updating fields on it.
"""

from typing import TypedDict, List, Dict, Optional


class SearchResult(TypedDict):
    sub_question: str
    content: str
    sources: List[str]


class AgentState(TypedDict):
    # The original question the user asked
    query: str

    # Sub-questions generated by the Planner node
    sub_questions: List[str]

    # Raw search results collected by the Search node (one entry per sub-question)
    search_results: List[SearchResult]

    # Final synthesized answer produced by the Synthesizer node
    final_summary: str

    # Tracks whether search came back empty, used for conditional routing
    search_failed: bool

    # Simple retry counter so the graph doesn't loop forever if search keeps failing
    retry_count: int

    # Any error message we want to surface to the user
    error: Optional[str]
